name: REUSE


on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'LICENSES/*'
    
jobs:
  Licensing:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup venv and activate it
      run: python3 -m venv venv/ && source venv/bin/activate
      shell: bash
    - name: Install REUSE
      run: pip install reuse
      shell: bash
    - name: Make source files REUSE-compliant
      run: reuse download GPL-2.0-only && reuse annotate --copyright="Qelectrotech Team <license@qelectrotech.org>" --license="GPL-2.0-only" source/developer/* source/users/* source/index.rst source/doc_changelog.rst --skip-unrecognised --recursive
    - name: Commit REUSE compliant files back to repo if there were changes
      run: |
        git config --global user.name "REUSE Github Action"
        git config --global user.email "action@github.com"
        git clean -f LICENSES/
        git commit -m "Files are now REUSE-compliant" -a
        git push
      id: back_commit
      continue-on-error: true   
